;CIS11
;The Assemblers (J Miguel Belarmino, Keisha Coleen Wagas, Joshua Barajas)
;Course Project-Option B
;Description: Test Score Calculator
;Inputs: 5 test scores
;Outputs: Minimum score, maximum score, average score, and letter grade
;Run: Assemble and run in LC-3 simulator
.ORIG x3000
Main
	LEA R0, WELCOME  ;PRINTS THE WELCOME MESSAGE
	PUTS
	;PROGRAM WILL STARTS HERE
	;STEP 1: INPUT 5 TEST SCORE
	JSR INPUTS	 ;Inputing function
	;STEP 2: FIND MIN SCORE
	JSR FINDMIN	 ;fIND THE MINIMUM
	;STEP 3: FIND MAX SCORE 

	;STEP 4: FIND AVG SCORE

	;STEP 5: FIND LETTER GRADE 

	;STEP 6: PRINT RESULT

	HALT

;STEP 1
INPUTS
	ST R1, SAVER1	;STORE R1
	ST R2, SAVER2	;STORE R2
	ST R3, SAVER3	;STORE R3
	ST R4, SAVER4	;STORE R4
	ST R5, SAVER5	;STORE R5
	ST R6, SAVER6	;STORE R6
	ST R7, SAVER7	;STORE WHERE TO RETURN BACK IN MAIN

	LEA R1, SCORES	;R1 WILL POINT TO THE SCORES ARRAY
	AND R2, R2, #0	;CLEAR R2
	ADD R2, R2, #5	;WE NEED TO INPUT 5 SCORES
INLOOP			;START OF LOOP TO GET 5 SCORES
	LEA R0, PROMPT	;ASK USER TO ENTER SCORE
	PUTS
	GETC		;GET FIRST NUMBER
	OUT		;SHOW INPUT
	LD R3, ASCIIZERO ;ASCII VALUE OF ZERO 
	NOT R3, R3	;FLIP BITS
	ADD R3, R3, #1	;MAKE IT NEGATIVE
	ADD R4, R0, R3	;CHANGE ASCII TO REAL NUMBER

	;MULTIPLY FIRST DIGIT BY 10
	ADD R5, R4, R4	;R5 = FIRST DIGIT X 2
	ADD R5, R5, R5	;R5 = FIRST DIGIT X 4
	ADD R5, R5, R5	;R5 = FIRST DIGIT X 8
	ADD R5, R5, R4	;R5 = FIRST DIGIT X 9
	ADD R5, R5, R4	;R5 = FIRST DIGIT X 10

	GETC		;GET SECOND NUMBER
	OUT		;SHOW INPUT
	LD R3, ASCIIZERO ;ASCII VALUE OF ZERO 
	NOT R3, R3	;FLIP BITS
	ADD R3, R3, #1	;MAKE IT NEGATIVE
	ADD R6, R0, R3	;CHANGE ASCII TO REAL NUMBER

	ADD R5, R5, R6	;FINAL SCORE = FIRST DIGIT X 10 + SECOND DIGIT
	STR R5, R1, #0	;SAVE SCORE INSIDE ARRAY
	ADD R1, R1, #1	;MOVE TO NEXT ARRAY SPOT
	LD R3, SUM	;LOAD CURRENT SUM
	ADD R3, R3, R5	;ADD THE NEW SCORE TO SUM
	ST R3, SUM	;SAVE THE NEW SUM
	LEA R0, NEWLINE	;MOVE TO NEXT LINE

	PUTS

	ADD R2, R2, #-1	;SUBTRACT 1 FROM COUNTER
	BRp INLOOP	;KEEP LOOPING UNTIL 5 SCORES ARE DONE

	LD R1, SAVER1	;RESTORE R1
	LD R2, SAVER2	;RESTORE R2
	LD R3, SAVER3	;RESTORE R3
	LD R4, SAVER4	;RESTORE R4
	LD R5, SAVER5	;RESTORE R5
	LD R6, SAVER6	;RESTORE R6
	LD R7, SAVER7	;RESTORE RETURN ADDRESS

	RET		;GO BACK TO MAIN

;STEP 2
FINDMIN
	ST R1, SAVER1	;STORE R1
	ST R2, SAVER2	;STORE R2
	ST R3, SAVER3	;STORE R3
	ST R4, SAVER4	;STORE R4
	ST R5, SAVER5	;STORE R5
	ST R6, SAVER6	;STORE R6
	ST R7, SAVER7	;STORE WHERE TO RETURN BACK IN MAIN

	LEA R1, SCORES	;R1 POINTS TO SCORES ARRAY
	LDR R3, R1, #0	;GET FIRST SCORE
	ST R3, MIN	;FIRST SCORE IS MIN FOR NOW
	ADD R1, R1, #1	;MOVE TO SECOND SCORE
	AND R2, R2, #0	;CLEAR R2
	ADD R2, R2, #4	;CHECK THE OTHER 4 SCORES
MINLOOP			;START LOOP TO FIND MIN
	LDR R4, R1, #0	;GET NEXT SCORE
	LD R3, MIN	;LOAD CURRENT MIN
	NOT R5, R3	;FLIP CURRENT MIN
	ADD R5, R5, #1	;MAKE CURRENT MIN NEGATIVE
	ADD R5, R4, R5	;COMPARE NEXT SCORE WITH MIN
	BRn NEWMIN	;IF NEXT SCORE IS SMALLER, SAVE IT
NEXTMIN
	ADD R1, R1, #1	;MOVE TO NEXT SCORE
	ADD R2, R2, #-1	;COUNT DOWN
	BRp MINLOOP	;KEEP CHECKING UNTIL DONE
	
	LD R1, SAVER1	;RESTORE R1
	LD R2, SAVER2	;RESTORE R2
	LD R3, SAVER3	;RESTORE R3
	LD R4, SAVER4	;RESTORE R4
	LD R5, SAVER5	;RESTORE R5
	LD R6, SAVER6	;RESTORE R6
	LD R7, SAVER7	;RESTORE RETURN ADDRESS

	RET		;GO BACK TO MAIN
NEWMIN
	ST R4, MIN	;SAVE NEW LOWEST SCORE
	BRnzp NEXTMIN	;GO BACK TO LOOP

;DATA

WELCOME .STRINGZ "TEST SCORE CALCULATOR\n"
PROMPT  .STRINGZ "Enter score: "
NEWLINE .STRINGZ "\n"

ASCIIZERO .FILL x0030
SCORES  .BLKW 5
SUM     .FILL #0
MIN     .FILL #0
MAX     .FILL #0
AVG     .FILL #0
GRADE   .FILL #0

SAVER1  .FILL #0

SAVER2  .FILL #0

SAVER3  .FILL #0

SAVER4  .FILL #0

SAVER5  .FILL #0

SAVER6  .FILL #0
SAVER7  .FILL #0


.END
